export { default as Navbar } from './navbar'
export { default as Footer } from './footer'
export { default as Layout } from './layout'
export { default as Meta } from './meta'
export { default as Hero } from './hero'
export { default as Projects } from './projects'
export { default as Contact } from './contact'
export { default as About } from './about'
